version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "--reload", "app:app"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
